let subData = 
[{"theme":"시대","country":"일본","begin":1868,"end":"1912","layer":2,"title":"메이지 시대 (明治)","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"시대","country":"일본","begin":1912,"end":"1926","layer":2,"title":"다이쇼 시대 (大正)","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"시대","country":"일본","begin":1926,"end":"1989","layer":2,"title":"쇼와 시대 (昭和)","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"시대","country":"일본","begin":1989,"end":"2019","layer":2,"title":"헤이세이 시대 (平成)","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"시대","country":"일본","begin":2019,"end":"2025","layer":2,"title":"레이와 시대 (令和)","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"시대","country":"일본","begin":1905,"end":"null","layer":1,"title":"제국주의국가 수립","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"시대","country":"일본","begin":1945,"end":"null","layer":2,"title":"공산주의국가 수립","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"분쟁","country":"일본 ","begin":1931,"end":"null","layer":3,"title":"만주사변(제2차 중일전쟁)","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"분쟁","country":"중국","begin":1840,"end":"1842","layer":3,"title":"아편전쟁","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"분쟁","country":"일본","begin":1875,"end":"null","layer":3,"title":"운양호 사건(雲揚号事件)","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"분쟁","country":"일본","begin":1904,"end":"null","layer":3,"title":"러일전쟁","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"분쟁","country":"중국","begin":1926,"end":"null","layer":3,"title":"북벌전쟁","desc":"1926년 7월 ","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"분쟁","country":"중국, 일본","begin":1945,"end":"1953","layer":1,"title":"중일전쟁","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"분쟁","country":"한국","begin":1950,"end":"null","layer":3,"title":"6동란(六動亂)","desc":"한국전쟁(6·25 전쟁)을 의미","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"분쟁","country":"일본","begin":1945,"end":"null","layer":5,"title":"제 2차 세계대전","desc":"1933년 3월 국제연맹 탈퇴 나 1937년 7월 중일전쟁 발발 등, 1945년 제2차 세계 대전 패전까지 일본이 국제 사회에서 빠른 속도로 고립되던 때였다","cite":"論)일본어 가로·세로짜기 혼용에 담긴 화양절충(和洋折衷)의 영향"},
    {"theme":"분쟁","country":"일본","begin":1941,"end":"1945","layer":6,"title":"태평양 전쟁","desc":"태평양전쟁기 (1941-45)에 발간한 「프론트(FRONT, 1942-45)」와 같은 대외선전잡지는 당시 유명한 해외 서적의 레이아웃과 그래픽 스타일을 그대로 모방하거나 외국어 버전으로만 발간하는 등 서구 형식을 있는 그대로 차용하는 행보를 보이기도 했다.","cite":"論)일본어 가로·세로짜기 혼용에 담긴 화양절충(和洋折衷)의 영향"},
    {"theme":"민족운동","country":"중국","begin":1861 ,"end":"1894","layer":4,"title":"양무 洋務 운동","desc":"개혁운동","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"민족운동","country":"중국","begin":1900,"end":"null","layer":4,"title":"농민들의 중심으로 의화단운동","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"민족운동","country":"중국","begin":1919,"end":"null","layer":4,"title":"5.4운동","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"민족운동","country":"한국","begin":1919 ,"end":"null","layer":6,"title":"항일독립운동인 3·1운동","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"민족운동","country":"한국","begin":1945,"end":"null","layer":4,"title":"한국 독립","desc":"8.15 독립","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"민족운동","country":"중국","begin":1978,"end":"null","layer":4,"title":"개혁개방 ","desc":"중국의 문화산업은 1979년 TV 방송에서 처음으로 상업광고가 허가되면서 시작되었다.","cite":""},
    {"theme":"조약","country":"일본","begin":1871,"end":"null","layer":5,"title":"청일수호조약의 체결","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"조약","country":"중국","begin":1901,"end":"null","layer":5,"title":"신축조약辛丑條約","desc":"서양의 11개국은 1901년 북경에서 신축조약辛丑條約을 성립","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"조약","country":"일본,한국","begin":1876,"end":"null","layer":6,"title":"한일수호조약 체결","desc":"1876년 2월 26일 ","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"조약","country":"일본 ","begin":1933,"end":"null","layer":5,"title":"국제연맹 탈퇴","desc":"","cite":""},
    {"theme":"조약","country":"한국","begin":1905,"end":"null","layer":6,"title":"을사조약","desc":"1905년 11월 17일, 일본이 대한제국을 강제로 외교권을 박탈하기 위해 체결한 조약","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"혁명","country":"중국","begin":1911,"end":"null","layer":5,"title":"신해혁명","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"혁명","country":"중국","begin":1917,"end":"null","layer":5,"title":"문학혁명文學革命 ","desc":"","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"},
    {"theme":"서양 ","country":"미국","begin":1929 ,"end":"null","layer":4,"title":"미국 대공황","desc":"미국 대공황으로 자본주의 국가들은 경제 위기에 직면하였다.","cite":"論)한· 중· 일 잡지표지 타이포그라피 비교 연구"}]